#!/bin/bash

# Run a blue green deployment
# TODO: Implement ;-)
image::run() {
  echo "Running a blue-green deployment"
}

image::description() {
  echo "Deploy with a blue-green strategy"
}

image::usage() {
  cat <<EOT
  -d --deployment <name>    Name of deployment for which to perform a blue-green deployment (mandatory)
  -i --image <image>        Full image name of the target version, including tag (mandatory)
EOT
}
